apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pro
  template:
    metadata:
      labels:
        app: pro
    spec:
      containers:
      - image: okteto.dev/pro:latest
        name: pro
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "63cdc6f9-4b30-4ed6-85b9-ba4a5d0b9601"
        - name: Vless_Path
          value: "/ftuxfraefygikvgcgxses"
        - name: Vmess_UUID
          value: "6f959dfe-d0b7-4eb2-82e2-7de14b9a47c8"
        - name: Vmess_Path
          value: "/erdytuibhgvxdzesdyguhi"
        - name: Share_Path
          value: "/v2link"
